version: "3.3"
services:

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - df_rabbit
  
networks:
  df_rabbit:
    external: true

  # simple_worker:
  #   build: './simple_worker'
  #   user: nobody
  #   depends_on:
  #     - rabbit
  #     - flask_app
